name: /mnt/c/Users/susum/tjrj-scraping/conda-env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - attrs=19.3.0=py_0
  - blas=1.0=openblas
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.27=0
  - cairo=1.16.0=hfb77d84_1002
  - certifi=2019.11.28=py37_0
  - dbus=1.13.6=he372182_0
  - entrypoints=0.3=py37_1000
  - expat=2.2.5=he1b5a44_1004
  - ffmpeg=4.1.3=h167e202_0
  - flake8=3.7.9=py37_0
  - flake8-polyfill=1.0.2=py_0
  - flake8-quotes=2.1.1=py_0
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.0=he983fc9_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_1
  - glib=2.58.3=py37h6f030ca_1002
  - gmp=6.1.2=hf484d3e_1000
  - gnutls=3.6.5=hd3a4fd2_1002
  - graphite2=1.3.13=hf484d3e_1000
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - harfbuzz=2.4.0=h9f30f68_3
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=64.2=he1b5a44_1
  - importlib_metadata=1.4.0=py37_0
  - jasper=1.900.1=h07fcdf6_1006
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - lame=3.100=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libclang=9.0.1=default_hde54327_0
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_4
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=14_openblas
  - liblapacke=3.8.0=14_openblas
  - libllvm9=9.0.1=hc9558a2_0
  - libopenblas=0.3.7=h5ec1e0e_6
  - libopencv=4.2.0=py37_1
  - libpng=1.6.37=hed695b0_0
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.9.1=hebb1f50_0
  - libxml2=2.9.10=hee79883_0
  - lz4-c=1.8.3=he1b5a44_1001
  - mccabe=0.6.1=py_1
  - more-itertools=8.1.0=py_0
  - ncurses=6.1=hf484d3e_1002
  - nettle=3.4.1=h1bed415_1002
  - nspr=4.24=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.17.4=py37hd5be1e1_0
  - numpy-base=1.17.4=py37h2f8d375_0
  - olefile=0.46=py_0
  - opencv=4.2.0=py37_1
  - openh264=1.8.0=hdbcaa40_1000
  - openssl=1.1.1d=h7b6447c_3
  - packaging=20.0=py_0
  - pcre=8.43=he1b5a44_0
  - pep8-naming=0.9.1=py_0
  - pillow=7.0.0=py37hefe7db6_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h516909a_1003
  - pluggy=0.12.0=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - py=1.8.1=py_0
  - py-opencv=4.2.0=py37h5ca1d4c_1
  - pycodestyle=2.5.0=py_0
  - pyflakes=2.1.1=py_0
  - pyparsing=2.4.6=py_0
  - pytesseract=0.3.1=py_0
  - pytest=5.3.2=py37_0
  - python=3.7.6=h357f687_2
  - qt=5.12.5=hd8c4c69_1
  - readline=8.0=hf8c457e_0
  - scikit-learn=0.22.1=py37h22eb022_0
  - scipy=1.3.2=py37he2b7bc3_0
  - setuptools=45.0.0=py37_1
  - six=1.14.0=py37_0
  - sqlite=3.30.1=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - wcwidth=0.1.8=py_0
  - wheel=0.33.6=py37_0
  - x264=1!152.20180806=h14c3975_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zipp=1.0.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
prefix: /mnt/c/Users/susum/tjrj-scraping/conda-env
